mirrors: Use a token secret in the autotagger
We're going to want to trigger some other actions on tag, but taggings
with the default GITHUB_TOKEN specifically do not trigger other actions.

So we'll need to add a token secret to all the mirrors using autotagger.
Added a tool to do mass updates of repo secrets to help with that.

diff --git a/.github/files/gh-autotagger/workflows/autotagger.yml b/.github/files/gh-autotagger/workflows/autotagger.yml
--- a/.github/files/gh-autotagger/workflows/autotagger.yml
+++ b/.github/files/gh-autotagger/workflows/autotagger.yml
@@ -9,7 +9,21 @@ jobs:
     name: Tag
     runs-on: ubuntu-latest
     steps:
+      - name: Check that the secret is set
+        env:
+          TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
+        run:
+          if [[ -z "$TOKEN" ]]; then
+            echo '::error::The secret API_TOKEN_GITHUB must be set.'
+            exit 1
+          fi
+
       - uses: actions/checkout@v2
+        with:
+          # We want to potentially trigger "tag" events, but the default GITHUB_TOKEN
+          # explicitly does not trigger events.
+          token: ${{ secrets.API_TOKEN_GITHUB }}
+
       - name: Tag
         run: |
           VER=$(sed -nEe 's/^## \[?([^]]*)\]? - .*/\1/;T;p;q' CHANGELOG.md || true)
