fix indentaton

diff --git a/.github/workflows/block-performance.yml b/.github/workflows/block-performance.yml
--- a/.github/workflows/block-performance.yml
+++ b/.github/workflows/block-performance.yml
@@ -3,11 +3,11 @@ name: Jetpack block performance
 on:
   pull_request:
     paths-ignore:
-    - '**.md'
+      - '**.md'
   push:
     branches: [master]
     paths-ignore:
-    - '**.md'
+      - '**.md'
   schedule:
     - cron:  '0 */12 * * *'
 
@@ -15,90 +15,90 @@ jobs:
   block-performance:
     name: "Performance tests"
     runs-on: ubuntu-latest
-    timeout-minutes: 25  # 2021-04-16: Successful runs seem to take 11-17 minutes
+    timeout-minutes: 25  # 2021-10-7: Successful runs seem to take 15 minutes
     env:
       WP_USERNAME: wordpress
       WP_PASSWORD: wordpress
     steps:
-    - uses: actions/checkout@v2
+      - uses: actions/checkout@v2
 
-    - name: Setup tools
-      uses: ./.github/actions/tool-setup
-      with:
-        node: 14
+      - name: Setup tools
+        uses: ./.github/actions/tool-setup
+        with:
+          node: 14
 
-    - uses: actions/checkout@v2
-      with:
-        repository: 'WordPress/gutenberg'
-        path: 'gutenberg'
+      - uses: actions/checkout@v2
+        with:
+          repository: 'WordPress/gutenberg'
+          path: 'gutenberg'
 
-    - name: Build Gutenberg
-      working-directory: gutenberg
-      run: |
-        npm ci
-        npm run build
+      - name: Build Gutenberg
+        working-directory: gutenberg
+        run: |
+          npm ci
+          npm run build
 
-    - name: Build Production Jetpack
-      run: |
-        pnpm install
-        pnpx jetpack build plugins/jetpack -v --production
+      - name: Build Production Jetpack
+        run: |
+          pnpm install
+          pnpx jetpack build plugins/jetpack -v --production
 
-    - name: Environment set-up
-      working-directory: tools/e2e-commons
-      env:
-        CONFIG_KEY: ${{ secrets.E2E_CONFIG_KEY }}
-      run: |
-        pnpm install
-        pnpm config:decrypt
-        echo "    gutenberg/packages/e2e-tests/plugins/disable-animations.php: /var/www/html/wp-content/plugins/disable-animations.php" >> ../docker/jetpack-docker-config-default.yml
-        pnpm env:start
-        pnpm tunnel:on
-        pnpx jetpack docker --type e2e --name t1 wp plugin deactivate jetpack
-        mkdir results
+      - name: Environment set-up
+        working-directory: tools/e2e-commons
+        env:
+          CONFIG_KEY: ${{ secrets.E2E_CONFIG_KEY }}
+        run: |
+          pnpm install
+          pnpm config:decrypt
+          echo "    gutenberg/packages/e2e-tests/plugins/disable-animations.php: /var/www/html/wp-content/plugins/disable-animations.php" >> ../docker/jetpack-docker-config-default.yml
+          pnpm env:start
+          pnpm tunnel:on
+          pnpx jetpack docker --type e2e --name t1 wp plugin deactivate jetpack
+          mkdir results
 
-    - name: Run performance base test
-      working-directory: gutenberg
-      run: |
-        export WP_BASE_URL=$(cat ../tools/e2e-commons/config/tmp/e2e-tunnels.txt)
+      - name: Run performance base test
+        working-directory: gutenberg
+        run: |
+          export WP_BASE_URL=$(cat ../tools/e2e-commons/config/tmp/e2e-tunnels.txt)
 
-        # We use || to get away from some random request failures which does not affect the results but generating non-zero exit code.
-        npm run test-performance packages/e2e-tests/specs/performance/post-editor.test.js || true
-        mv packages/e2e-tests/specs/performance/post-editor.test.results.json ../tools/e2e-commons/results/base.test.results.json
+          # We use || to get away from some random request failures which does not affect the results but generating non-zero exit code.
+          npm run test-performance packages/e2e-tests/specs/performance/post-editor.test.js || true
+          mv packages/e2e-tests/specs/performance/post-editor.test.results.json ../tools/e2e-commons/results/base.test.results.json
 
-    - name: Set up Jetpack connection
-      working-directory: tools/e2e-commons
-      env:
-        CONFIG_KEY: ${{ secrets.E2E_CONFIG_KEY }}
-      run: |
-        pnpm env:reset
-        pnpm tunnel:reset
-        pnpm jetpack-connect
-        pnpx jetpack docker --type e2e --name t1 wp plugin activate jetpack
-        pnpx jetpack docker --type e2e --name t1 wp jetpack module deactivate sso
+      - name: Set up Jetpack connection
+        working-directory: tools/e2e-commons
+        env:
+          CONFIG_KEY: ${{ secrets.E2E_CONFIG_KEY }}
+        run: |
+          pnpm env:reset
+          pnpm tunnel:reset
+          pnpm jetpack-connect
+          pnpx jetpack docker --type e2e --name t1 wp plugin activate jetpack
+          pnpx jetpack docker --type e2e --name t1 wp jetpack module deactivate sso
 
-    - name: Run performance Jetpack test
-      working-directory: gutenberg
-      run: |
-        export WP_BASE_URL=$(cat ../tools/e2e-commons/config/tmp/e2e-tunnels.txt)
+      - name: Run performance Jetpack test
+        working-directory: gutenberg
+        run: |
+          export WP_BASE_URL=$(cat ../tools/e2e-commons/config/tmp/e2e-tunnels.txt)
 
-        # We use || to get away from some random request failures which does not affect the results but generating non-zero exit code.
-        npm run test-performance packages/e2e-tests/specs/performance/post-editor.test.js || true
-        mv packages/e2e-tests/specs/performance/post-editor.test.results.json ../tools/e2e-commons/results/jetpack.test.results.json
+          # We use || to get away from some random request failures which does not affect the results but generating non-zero exit code.
+          npm run test-performance packages/e2e-tests/specs/performance/post-editor.test.js || true
+          mv packages/e2e-tests/specs/performance/post-editor.test.results.json ../tools/e2e-commons/results/jetpack.test.results.json
 
-    - name: Environment tear-down
-      if: ${{ always() }}
-      working-directory: tools/e2e-commons
-      continue-on-error: true
-      run: |
-        pnpm run tunnel-off
+      - name: Environment tear-down
+        if: ${{ always() }}
+        working-directory: tools/e2e-commons
+        continue-on-error: true
+        run: |
+          pnpm run tunnel-off
 
-    - name: Upload test artifacts
-      if: ${{ always() }}
-      continue-on-error: true
-      uses: actions/upload-artifact@v2
-      with:
-        name: test-output-block-perf
-        path: tools/e2e-commons/results
+      - name: Upload test artifacts
+        if: ${{ always() }}
+        continue-on-error: true
+        uses: actions/upload-artifact@v2
+        with:
+          name: test-output-block-perf
+          path: tools/e2e-commons/results
 
   test-reports:
     name: "Trigger test report workflow"
