ci: Run tests using GitHub parallel steps
GitHub now has native support for parallel steps. Let's try converting
our Tests job to use those as "workers", which should allow for
non-interleaved output (unless the test itself does `concurrently` or
the like).

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -169,80 +169,91 @@ jobs:
         if: steps.changed.outputs.any-plugins == 'true' && matrix.wp != 'none'
         run: .github/files/setup-wordpress-env.sh
 
-      - name: Run project tests
-        id: run-tests
+      - name: Prepare test queue
         env:
-          FORCE_PACKAGE_TESTS: ${{ case( matrix.force-package-tests, 'true', 'false' ) }}
-          CHANGED: ${{ steps.changed.outputs.projects }}
+          QUEUEFILE: ${{ runner.temp }}/testqueue
         run: |
-          EXIT=0
-          declare -A PIDS
-          PIDS=()
-          MAXPIDS=$( nproc )
-          FAILED=()
           mkdir artifacts
           [[ -n "$COVERAGE_GROUP" ]] && mkdir coverage
           for P in composer.json projects/*/*/composer.json; do
-            if [[ ${#PIDS[@]} -ge $MAXPIDS ]]; then
-              if ! wait -fn -p PID "${!PIDS[@]}"; then
-                echo "::error::Tests for ${PIDS[$PID]} failed!"
-                FAILED+=( "${PIDS[$PID]}" )
-                EXIT=1
+            echo "$P"
+          done > "$QUEUEFILE"
+
+      - parallel:
+        - &testworker
+          name: Run project tests
+          env:
+            FORCE_PACKAGE_TESTS: ${{ case( matrix.force-package-tests, 'true', 'false' ) }}
+            CHANGED: ${{ steps.changed.outputs.projects }}
+            QUEUEFILE: ${{ runner.temp }}/testqueue
+          run: |
+            EXIT=0
+
+            function cleanup {
+              # Actions seems to slow down if there are a lot of files, so clean up Composer stuff after each test.
+              # We don't do it for JS stuff, as that might break things with how JS does package deps.
+              rm -rf "$DIR/vendor" "$DIR/jetpack_vendor" "$DIR/wordpress"
+            }
+
+            function failgroup {
+              EXIT=1
+              echo "::endgroup::"
+              echo "::error::$1"
+              cleanup
+            }
+
+            while true; do
+              P=$( flock "$QUEUEFILE" sed -i -e '1{w/dev/stdout' -e 'd}' )
+              [[ -z "$P" ]] && break
+
+              if [[ "$P" == "composer.json" ]]; then
+                DIR="."
+                SLUG="monorepo"
+              else
+                DIR="${P%/composer.json}"
+                SLUG="${DIR#projects/}"
               fi
-              echo "Finished ${PIDS[$PID]}"
-              unset PIDS[$PID]
-            fi
 
-            if [[ "$P" == "composer.json" ]]; then
-              DIR="."
-              SLUG="monorepo"
-            else
-              DIR="${P%/composer.json}"
-              SLUG="${DIR#projects/}"
-            fi
+              if [[ "${SLUG%%/*}" != "plugins" && "$WP_BRANCH" != 'latest' && "$WP_BRANCH" != 'none' && "$FORCE_PACKAGE_TESTS" != "true" ]]; then
+                echo "Skipping $SLUG, only plugins run for WP_BRANCH = $WP_BRANCH"
+                continue
+              fi
 
-            if [[ "${SLUG%%/*}" != "plugins" && "$WP_BRANCH" != 'latest' && "$WP_BRANCH" != 'none' && "$FORCE_PACKAGE_TESTS" != "true" ]]; then
-              echo "Skipping $SLUG, only plugins run for WP_BRANCH = $WP_BRANCH"
-              continue
-            fi
-
-            if ! jq --argjson changed "$CHANGED" --arg p "$SLUG" -ne '$changed[$p] // false' > /dev/null; then
-              echo "Skipping $SLUG, no changes in it or its dependencies"
-            elif ! jq --arg script "$TEST_SCRIPT" -e '.scripts[$script] // false' "$P" > /dev/null; then
-              echo "Skipping $SLUG, no test script is defined in composer.json"
-            elif php -r 'exit( preg_match( "/^>=\\s*(\\d+\\.\\d+)$/", $argv[1], $m ) && version_compare( PHP_VERSION, $m[1], "<" ) ? 0 : 1 );' "$( jq -r '.require.php // ""' "$P" )"; then
-              echo "Skipping $SLUG, requires PHP $( jq -r '.require.php // ""' "$P" ) but PHP version is $( php -r 'echo PHP_VERSION;' )"
-            else
-              if jq --arg script "skip-$TEST_SCRIPT" -e '.scripts[$script] // false' "$P" > /dev/null; then
-                { composer --working-dir="$DIR" run "skip-$TEST_SCRIPT"; CODE=$?; } || true
-                if [[ $CODE -eq 3 ]]; then
-                  echo "Skipping tests for $SLUG due to skip-$TEST_SCRIPT script"
-                  continue
-                elif [[ $CODE -ne 0 ]]; then
-                  echo "::error::Script skip-$TEST_SCRIPT failed to run $CODE!"
-                  FAILED+=( "$SLUG" )
-                  EXIT=1
-                  continue
+              if ! jq --argjson changed "$CHANGED" --arg p "$SLUG" -ne '$changed[$p] // false' > /dev/null; then
+                echo "Skipping $SLUG, no changes in it or its dependencies"
+              elif ! jq --arg script "$TEST_SCRIPT" -e '.scripts[$script] // false' "$P" > /dev/null; then
+                echo "Skipping $SLUG, no test script is defined in composer.json"
+              elif php -r 'exit( preg_match( "/^>=\\s*(\\d+\\.\\d+)$/", $argv[1], $m ) && version_compare( PHP_VERSION, $m[1], "<" ) ? 0 : 1 );' "$( jq -r '.require.php // ""' "$P" )"; then
+                echo "Skipping $SLUG, requires PHP $( jq -r '.require.php // ""' "$P" ) but PHP version is $( php -r 'echo PHP_VERSION;' )"
+              else
+                if jq --arg script "skip-$TEST_SCRIPT" -e '.scripts[$script] // false' "$P" > /dev/null; then
+                  { composer --working-dir="$DIR" run "skip-$TEST_SCRIPT"; CODE=$?; } || true
+                  if [[ $CODE -eq 3 ]]; then
+                    echo "Skipping tests for $SLUG due to skip-$TEST_SCRIPT script"
+                    continue
+                  elif [[ $CODE -ne 0 ]]; then
+                    echo "::error::Script skip-$TEST_SCRIPT failed to run $CODE!"
+                    EXIT=1
+                    continue
+                  fi
                 fi
-              fi
 
-              echo "Running tests for $SLUG"
-              {
+                echo "::group::Running tests for $SLUG"
                 # Composer install, if appropriate. Note setup-wordpress-env.sh did it already for plugins.
                 if [[ "${SLUG%%/*}" != "plugins" && ( "$TEST_SCRIPT" == "test-php" || "$TEST_SCRIPT" == "test-php-coverage" ) ]]; then
                   if [[ ! -f "$DIR/composer.lock" ]]; then
                     echo 'No composer.lock, running `composer update`'
-                    composer --working-dir="$DIR" update
+                    composer --working-dir="$DIR" update || { failgroup "Composer update for $SLUG failed"; continue; }
                   elif composer --working-dir="$DIR" check-platform-reqs --lock; then
                     echo 'Platform reqs pass, running `composer install`'
-                    composer --working-dir="$DIR" install
+                    composer --working-dir="$DIR" install || { failgroup "Composer install for $SLUG failed"; continue; }
                     if composer info --locked phpunit/phpunit &>/dev/null; then
                       echo 'Updating PHPUnit in case a newer version than locked is usable'
-                      composer --working-dir="$DIR" update -W phpunit/phpunit
+                      composer --working-dir="$DIR" update -W phpunit/phpunit || { failgroup "Composer update for $SLUG failed"; continue; }
                     fi
                   else
                     echo 'Platform reqs failed, running `composer update`'
-                    composer --working-dir="$DIR" update
+                    composer --working-dir="$DIR" update || { failgroup "Composer update for $SLUG failed"; continue; }
                   fi
                 fi
 
@@ -256,40 +267,17 @@ jobs:
                   mkdir -p "coverage/$SLUG"
                   export COVERAGE_DIR="$GITHUB_WORKSPACE/coverage/$SLUG"
                 fi
-                FAIL=false
-                if ! composer run --timeout=0 --working-dir="$DIR" "$TEST_SCRIPT"; then
-                  FAIL=true
-                fi
+                composer run --timeout=0 --working-dir="$DIR" "$TEST_SCRIPT" || { failgroup "Tests for $SLUG failed"; continue; }
 
-                # Actions seems to slow down if there are a lot of files, so clean up Composer stuff after each test.
-                # We don't do it for JS stuff, as that might break things with how JS does package deps.
-                rm -rf "$DIR/vendor" "$DIR/jetpack_vendor" "$DIR/wordpress"
-
-                if $FAIL; then
-                  echo "Tests for $SLUG failed!"
-                  exit 1
-                fi
-              } 2> >( sed -u 's!^!['"$SLUG"'] !' >&2 ) > >( sed -u 's!^!['"$SLUG"'] !' ) &
-              PIDS[$!]=$SLUG
-            fi
-          done
-          while [[ ${#PIDS[@]} -gt 0 ]]; do
-            if ! wait -fn -p PID "${!PIDS[@]}"; then
-              echo "::error::Tests for ${PIDS[$PID]} failed!"
-              FAILED+=( "${PIDS[$PID]}" )
-              EXIT=1
-            fi
-            echo "Finished ${PIDS[$PID]}"
-            unset PIDS[$PID]
-          done
-
-          if [[ ${#FAILED[@]} -gt 0 ]]; then
-            echo ''
-            echo 'The following tests failed:'
-            printf " - %s\n" "${FAILED[@]}"
-          fi
-
-          exit $EXIT
+                echo "::endgroup::"
+                echo "Tests for $SLUG passed"
+                cleanup
+              fi
+            done
+            exit $EXIT
+        - *testworker
+        - *testworker
+        - *testworker
 
       - name: Process coverage results
         id: process-coverage
