Bring back line prefixing, for the raw log view

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -238,38 +238,40 @@ jobs:
                   fi
                 fi
 
-                echo "::group::Running tests for $SLUG"
-                # Composer install, if appropriate. Note setup-wordpress-env.sh did it already for plugins.
-                if [[ "${SLUG%%/*}" != "plugins" && ( "$TEST_SCRIPT" == "test-php" || "$TEST_SCRIPT" == "test-php-coverage" ) ]]; then
-                  if [[ ! -f "$DIR/composer.lock" ]]; then
-                    echo 'No composer.lock, running `composer update`'
-                    composer --working-dir="$DIR" update || { failgroup "Composer update for $SLUG failed"; continue; }
-                  elif composer --working-dir="$DIR" check-platform-reqs --lock; then
-                    echo 'Platform reqs pass, running `composer install`'
-                    composer --working-dir="$DIR" install || { failgroup "Composer install for $SLUG failed"; continue; }
-                    if composer info --locked phpunit/phpunit &>/dev/null; then
-                      echo 'Updating PHPUnit in case a newer version than locked is usable'
-                      composer --working-dir="$DIR" update -W phpunit/phpunit || { failgroup "Composer update for $SLUG failed"; continue; }
+                {
+                  echo "::group::Running tests for $SLUG"
+                  # Composer install, if appropriate. Note setup-wordpress-env.sh did it already for plugins.
+                  if [[ "${SLUG%%/*}" != "plugins" && ( "$TEST_SCRIPT" == "test-php" || "$TEST_SCRIPT" == "test-php-coverage" ) ]]; then
+                    if [[ ! -f "$DIR/composer.lock" ]]; then
+                      echo 'No composer.lock, running `composer update`'
+                      composer --working-dir="$DIR" update || { failgroup "Composer update for $SLUG failed"; continue; }
+                    elif composer --working-dir="$DIR" check-platform-reqs --lock; then
+                      echo 'Platform reqs pass, running `composer install`'
+                      composer --working-dir="$DIR" install || { failgroup "Composer install for $SLUG failed"; continue; }
+                      if composer info --locked phpunit/phpunit &>/dev/null; then
+                        echo 'Updating PHPUnit in case a newer version than locked is usable'
+                        composer --working-dir="$DIR" update -W phpunit/phpunit || { failgroup "Composer update for $SLUG failed"; continue; }
+                      fi
+                    else
+                      echo 'Platform reqs failed, running `composer update`'
+                      composer --working-dir="$DIR" update || { failgroup "Composer update for $SLUG failed"; continue; }
                     fi
-                  else
-                    echo 'Platform reqs failed, running `composer update`'
-                    composer --working-dir="$DIR" update || { failgroup "Composer update for $SLUG failed"; continue; }
                   fi
-                fi
 
-                if [[ "${SLUG%%/*}" == "plugins" ]]; then
-                  export WP_TESTS_CONFIG_FILE_PATH="$WORDPRESS_DEVELOP_DIR/wp-tests-config.${SLUG##*/}.php"
-                fi
+                  if [[ "${SLUG%%/*}" == "plugins" ]]; then
+                    export WP_TESTS_CONFIG_FILE_PATH="$WORDPRESS_DEVELOP_DIR/wp-tests-config.${SLUG##*/}.php"
+                  fi
 
-                mkdir -p "artifacts/$SLUG"
-                export ARTIFACTS_DIR="$GITHUB_WORKSPACE/artifacts/$SLUG"
-                if [[ -n "$COVERAGE_GROUP" ]]; then
-                  mkdir -p "coverage/$SLUG"
-                  export COVERAGE_DIR="$GITHUB_WORKSPACE/coverage/$SLUG"
-                fi
-                composer run --timeout=0 --working-dir="$DIR" "$TEST_SCRIPT" || { failgroup "Tests for $SLUG failed"; continue; }
+                  mkdir -p "artifacts/$SLUG"
+                  export ARTIFACTS_DIR="$GITHUB_WORKSPACE/artifacts/$SLUG"
+                  if [[ -n "$COVERAGE_GROUP" ]]; then
+                    mkdir -p "coverage/$SLUG"
+                    export COVERAGE_DIR="$GITHUB_WORKSPACE/coverage/$SLUG"
+                  fi
+                  composer run --timeout=0 --working-dir="$DIR" "$TEST_SCRIPT" || { failgroup "Tests for $SLUG failed"; continue; }
 
-                echo "::endgroup::"
+                  echo "::endgroup::"
+                } 2> >( sed -u '/^::/!s!^!['"$SLUG"'] !' >&2 ) > >( sed -u '/^::/!s!^!['"$SLUG"'] !' )
                 echo "Tests for $SLUG passed"
                 cleanup
               fi
