Try this to keep output in order

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -188,20 +188,6 @@ jobs:
             QUEUEFILE: ${{ runner.temp }}/testqueue
           run: |
             EXIT=0
-
-            function cleanup {
-              # Actions seems to slow down if there are a lot of files, so clean up Composer stuff after each test.
-              # We don't do it for JS stuff, as that might break things with how JS does package deps.
-              rm -rf "$DIR/vendor" "$DIR/jetpack_vendor" "$DIR/wordpress"
-            }
-
-            function failgroup {
-              EXIT=1
-              echo "::endgroup::"
-              echo "::error::$1"
-              cleanup
-            }
-
             while true; do
               P=$( flock "$QUEUEFILE" sed -i -e '1{w/dev/stdout' -e 'd}' "$QUEUEFILE" )
               [[ -z "$P" ]] && break
@@ -240,23 +226,24 @@ jobs:
                   fi
                 fi
 
-                {
-                  echo "::group::Running tests for $SLUG"
+                echo "::group::Running tests for $SLUG"
+                FAIL=
+                while true; do
                   # Composer install, if appropriate. Note setup-wordpress-env.sh did it already for plugins.
                   if [[ "${SLUG%%/*}" != "plugins" && ( "$TEST_SCRIPT" == "test-php" || "$TEST_SCRIPT" == "test-php-coverage" ) ]]; then
                     if [[ ! -f "$DIR/composer.lock" ]]; then
                       echo 'No composer.lock, running `composer update`'
-                      composer --working-dir="$DIR" update || { failgroup "Composer update for $SLUG failed"; continue; }
+                      composer --working-dir="$DIR" update || { FAIL="Composer update for $SLUG failed"; break; }
                     elif composer --working-dir="$DIR" check-platform-reqs --lock; then
                       echo 'Platform reqs pass, running `composer install`'
-                      composer --working-dir="$DIR" install || { failgroup "Composer install for $SLUG failed"; continue; }
+                      composer --working-dir="$DIR" install || { FAIL="Composer install for $SLUG failed"; break; }
                       if composer info --locked phpunit/phpunit &>/dev/null; then
                         echo 'Updating PHPUnit in case a newer version than locked is usable'
-                        composer --working-dir="$DIR" update -W phpunit/phpunit || { failgroup "Composer update for $SLUG failed"; continue; }
+                        composer --working-dir="$DIR" update -W phpunit/phpunit || { FAIL="Composer update for $SLUG failed"; break; }
                       fi
                     else
                       echo 'Platform reqs failed, running `composer update`'
-                      composer --working-dir="$DIR" update || { failgroup "Composer update for $SLUG failed"; continue; }
+                      composer --working-dir="$DIR" update || { FAIL="Composer update for $SLUG failed"; break; }
                     fi
                   fi
 
@@ -270,12 +257,19 @@ jobs:
                     mkdir -p "coverage/$SLUG"
                     export COVERAGE_DIR="$GITHUB_WORKSPACE/coverage/$SLUG"
                   fi
-                  composer run --timeout=0 --working-dir="$DIR" "$TEST_SCRIPT" || { failgroup "Tests for $SLUG failed"; continue; }
+                  composer run --timeout=0 --working-dir="$DIR" "$TEST_SCRIPT" || { FAIL="Tests for $SLUG failed"; break; }
+                  break
+                done 2>&1 | sed -u '/^::/!s!^!['"$SLUG"'] !'
+                echo "::endgroup::"
+                if [[ -n "$FAIL" ]]; then
+                  echo "::error::$FAIL"
+                else
+                  echo "Tests for $SLUG passed"
+                fi
 
-                  echo "::endgroup::"
-                } 2> >( sed -u '/^::/!s!^!['"$SLUG"'] !' >&2 ) > >( sed -u '/^::/!s!^!['"$SLUG"'] !' )
-                echo "Tests for $SLUG passed"
-                cleanup
+                # Actions seems to slow down if there are a lot of files, so clean up Composer stuff after each test.
+                # We don't do it for JS stuff, as that might break things with how JS does package deps.
+                rm -rf "$DIR/vendor" "$DIR/jetpack_vendor" "$DIR/wordpress"
               fi
             done
             exit $EXIT
