Fix codesniffer test skipping
I knew there was a reason I hadn't done this before...

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -121,6 +121,18 @@ jobs:
             elif ! jq --arg script "$TEST_SCRIPT" -e '.scripts[$script] // false' "$P" > /dev/null; then
               echo "Skipping $SLUG, no test script is defined in composer.json"
             else
+              if jq --arg script "skip-$TEST_SCRIPT" -e '.scripts[$script] // false' "$P" > /dev/null; then
+                { composer --working-dir="$DIR" run "skip-$TEST_SCRIPT"; CODE=$?; } || true
+                if [[ $CODE -eq 3 ]]; then
+                  echo "Skipping tests for $SLUG due to skip-$TEST_SCRIPT script"
+                  continue
+                elif [[ $CODE -ne 0 ]]; then
+                  echo "::error::Script skip-$TEST_SCRIPT failed to run $CODE!"
+                  EXIT=1
+                  continue
+                fi
+              fi
+
               echo "::group::Running tests for $SLUG"
 
               # Composer install, if appropriate. Note setup-wordpress-env.sh did it already for plugins.
